preset: laravel

risky: true

linting:
  disable_cache: true

finder:
  exclude:
    - 'vendor'
    - 'storage'
    - 'tests/Fixtures'

fixers:
  braces: true
  cast_spaces: {space: single}
  concat_space: {spacing: one}
  declare_equal_normalize: {space: none}
  elseif: true
  encoding: true
  full_opening_tag: true
  function_declaration: true
  include: true
  line_ending: true
  lower_case_constants: true
  lower_case_keywords: true
  method_argument_space: {ensure_fully_multiline: true}
  no_closing_tag: true
  no_spaces_after_function_name: true
  no_spaces_inside_parenthesis: true
  no_trailing_whitespace: true
  no_trailing_whitespace_in_comment: true
  single_blank_line_at_eof: true
  single_class_element_per_statement: {elements: [const, property]}
  single_import_per_statement: true
  single_line_after_imports: true
  switch_case_semicolon_to_colon: true
  switch_case_space: true
  visibility_required: {elements: [const, method, property]}
  yoda_style: {equal: false, identical: false, less_and_greater: false}
